### PR TITLE
[FEATURE] Writing the 'phase' and 'precedingPhases' fields in a new way

### PR DESCRIPTION
**Pull request by storgashov**
This feature will supersede the old-fashion phases definition in the next drop.

### CODE REVIEW

**Comment by storgashov** [comment]
@dornatsky, should we merge this eventually? :)

**Comment by dornatsky** [comment]
what on earth is that

**Comment by dornatsky** [comment]
Hi @erkfel

**Comment by storgashov** [comment]
> what on earth is that

This is a task from qubell/vermilion#883:

> Update external manifests: ...

**Comment by erkfel** [comment]
Huh :)

**Pull request closed without merging**
